"""update boards table to add column updated_at

Revision ID: 257ad6689ecd
Revises: 0c48ad7f911c
Create Date: 2026-01-14 17:19:47.752264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257ad6689ecd'
down_revision: Union[str, Sequence[str], None] = '0c48ad7f911c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'updated_at')
    # ### end Alembic commands ###
