"""add performance indexes

Revision ID: d33407f7fb81
Revises: c75232f58aca
Create Date: 2026-01-27 21:53:16.257411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33407f7fb81'
down_revision: Union[str, Sequence[str], None] = 'c75232f58aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boards_created_at'), table_name='boards')
    op.create_index('idx_board_project_archived', 'boards', ['project_id', 'archived'], unique=False)
    op.create_index('idx_board_project_position', 'boards', ['project_id', 'position'], unique=False)
    op.create_index(op.f('ix_boards_archived'), 'boards', ['archived'], unique=False)
    op.create_index(op.f('ix_boards_position'), 'boards', ['position'], unique=False)
    op.create_index(op.f('ix_boards_project_id'), 'boards', ['project_id'], unique=False)
    op.create_index('idx_membership_user_project_role', 'memberships', ['user_id', 'project_id', 'role'], unique=False)
    op.create_index(op.f('ix_memberships_project_id'), 'memberships', ['project_id'], unique=False)
    op.create_index(op.f('ix_memberships_role'), 'memberships', ['role'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index('idx_task_board_archived', 'tasks', ['board_id', 'archived'], unique=False)
    op.create_index('idx_task_board_position', 'tasks', ['board_id', 'position'], unique=False)
    op.create_index('idx_task_status_priority', 'tasks', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_tasks_archived'), 'tasks', ['archived'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_board_id'), 'tasks', ['board_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_position'), 'tasks', ['position'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_position'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_board_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_archived'), table_name='tasks')
    op.drop_index('idx_task_status_priority', table_name='tasks')
    op.drop_index('idx_task_board_position', table_name='tasks')
    op.drop_index('idx_task_board_archived', table_name='tasks')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_role'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_project_id'), table_name='memberships')
    op.drop_index('idx_membership_user_project_role', table_name='memberships')
    op.drop_index(op.f('ix_boards_project_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_position'), table_name='boards')
    op.drop_index(op.f('ix_boards_archived'), table_name='boards')
    op.drop_index('idx_board_project_position', table_name='boards')
    op.drop_index('idx_board_project_archived', table_name='boards')
    op.create_index(op.f('ix_boards_created_at'), 'boards', ['created_at'], unique=False)
    # ### end Alembic commands ###
